package vn.kir.keiba;

import org.bukkit.command.*;import org.bukkit.entity.Player;import java.util.*;

final class KeibaCommand implements CommandExecutor,TabCompleter {
    private final KirKeibaPlugin plugin;private final RaceManager races;private final KeibaMenu menu;private final UpdateChecker updates;
    KeibaCommand(KirKeibaPlugin plugin,RaceManager races,KeibaMenu menu,UpdateChecker updates){this.plugin=plugin;this.races=races;this.menu=menu;this.updates=updates;}
    public boolean onCommand(CommandSender sender,Command command,String label,String[] args){if(args.length==0){if(sender instanceof Player p)menu.open(p);else if(races.waiting())sender.sendMessage(prefix()+races.waitingMessage());else sendHelp(sender);return true;}switch(args[0].toLowerCase()){case"help","huongdan"->{if(sender instanceof Player p)menu.openHelp(p);sendHelp(sender);}case"status"->{if(races.waiting())sender.sendMessage(prefix()+races.waitingMessage());else sender.sendMessage(prefix()+Text.color("&fVòng #"+races.raceId()+" &8• &e"+races.stateLabel()+" &8• &fcòn "+races.secondsLeft()+"s"));}case"tickets"->showTickets(sender);case"admin"->admin(sender,args);default->sendHelp(sender);}return true;}
    private void showTickets(CommandSender sender){if(!(sender instanceof Player p)){sender.sendMessage(prefix()+message("player-only"));return;}var tickets=races.playerTickets(p.getUniqueId());sender.sendMessage(prefix()+Text.color("&6Vé vòng #"+races.raceId()+": &f"+tickets.size()));for(BetTicket t:tickets)sender.sendMessage(Text.color("&7#"+t.id()+" &e"+t.type().label+" &f"+t.selection()+" &e"+RaceManager.money(t.stake())));}
    private void admin(CommandSender sender,String[] args){if(!sender.hasPermission("kirkeiba.admin")){sender.sendMessage(prefix()+message("no-permission"));return;}if(args.length<2||args[1].equalsIgnoreCase("help")){sendAdminHelp(sender);updates.report(sender,false);return;}String action=args[1].toLowerCase();String permission="kirkeiba.admin."+action;if(!sender.hasPermission(permission)){sender.sendMessage(prefix()+message("no-permission"));return;}switch(action){case"forcestart"->{races.forceStart();sender.sendMessage(prefix()+Text.color("&aĐã ép khóa cược."));}case"cancel"->{races.cancelAndRefund(sender.getName());sender.sendMessage(prefix()+Text.color("&aĐã hủy vòng và hoàn vé."));}case"reload"->{plugin.reloadConfig();sender.sendMessage(prefix()+Text.color("&aĐã nạp lại config. Danh sách ngựa cần restart."));}case"update"->updates.report(sender,true);case"reset"->reset(sender,args);default->sendAdminHelp(sender);}}
    private void reset(CommandSender sender,String[] args){if(args.length<4||!args[3].equalsIgnoreCase("confirm")){sender.sendMessage(Text.color("&cXác nhận bằng: /keiba admin reset <current|history|stats|all> confirm"));return;}String scope=args[2].toLowerCase();if(!List.of("current","history","stats","all").contains(scope)){sender.sendMessage(Text.color("&cPhạm vi không hợp lệ."));return;}sender.sendMessage(prefix()+Text.color("&a"+races.adminReset(scope,sender.getName())));}
    private void sendAdminHelp(CommandSender sender){List<String> lines=plugin.getConfig().getStringList("messages.admin-help");if(lines.isEmpty())lines=List.of("&6----- KIR Keiba Admin -----","&e/keiba admin update &7- Kiểm tra bản mới","&e/keiba admin forcestart &7- Khóa cược ngay","&e/keiba admin cancel &7- Hủy vòng và hoàn vé","&e/keiba admin reload &7- Nạp lại config","&e/keiba admin reset current confirm &7- Tạo lại vòng hiện tại","&e/keiba admin reset history confirm &7- Ẩn toàn bộ lịch sử kết quả","&e/keiba admin reset stats confirm &7- Xóa vé cũ và thống kê","&c/keiba admin reset all confirm &7- Reset toàn bộ dữ liệu");for(String line:lines)sender.sendMessage(Text.color(line));}
    private void sendHelp(CommandSender sender){for(String line:plugin.getConfig().getStringList("messages.help"))sender.sendMessage(Text.color(line));}private String prefix(){return Text.color(plugin.getConfig().getString("messages.prefix","&6[KIR Keiba]&r "));}private String message(String key){return Text.color(plugin.getConfig().getString("messages."+key,""));}
    public List<String> onTabComplete(CommandSender sender,Command command,String alias,String[] args){if(args.length==1)return filter(List.of("help","status","tickets","admin"),args[0]);if(!sender.hasPermission("kirkeiba.admin"))return List.of();if(args.length==2&&args[0].equalsIgnoreCase("admin"))return filter(List.of("help","update","forcestart","cancel","reload","reset"),args[1]);if(args.length==3&&args[1].equalsIgnoreCase("reset"))return filter(List.of("current","history","stats","all"),args[2]);if(args.length==4&&args[1].equalsIgnoreCase("reset"))return filter(List.of("confirm"),args[3]);return List.of();}
    private static List<String> filter(List<String> values,String prefix){return values.stream().filter(v->v.startsWith(prefix.toLowerCase())).toList();}
}
