package vn.kir.keiba;
import net.milkbowl.vault.economy.Economy;import org.bukkit.Bukkit;import org.bukkit.Sound;import org.bukkit.entity.Player;import org.bukkit.scheduler.BukkitTask;import java.nio.charset.StandardCharsets;import java.security.*;import java.util.*;

final class RaceManager {
    private final KirKeibaPlugin plugin;private final Economy economy;private final RaceRepository repository;private final SecureRandom random=new SecureRandom();private final List<HorseEntry> horses=new ArrayList<>();private final RaceBossBar bossBar;
    private BukkitTask ticker;private RaceState state;private long raceId,seed,deadline;private double lastOdds;private List<HorseEntry> result=List.of();private RaceConditions conditions=RaceConditions.neutral();
    RaceManager(KirKeibaPlugin p,Economy e,RaceRepository r){plugin=p;economy=e;repository=r;loadHorses();bossBar=new RaceBossBar(p);}
    void start()throws Exception{recover();openRace();bossBar.update(this);ticker=Bukkit.getScheduler().runTaskTimer(plugin,this::tick,20,20);}void shutdown(){if(ticker!=null)ticker.cancel();bossBar.close();}
    RaceState state(){return state;}long raceId(){return raceId;}double lastOdds(){return lastOdds;}long secondsLeft(){return Math.max(0,(deadline-System.currentTimeMillis()+999)/1000);}List<HorseEntry> horses(){return List.copyOf(horses);}List<HorseEntry> result(){return result;}
    String stateLabel(){return switch(state){case BETTING_OPEN->"Mở cược";case BETTING_LOCKED->"Đã khóa cược";case RUNNING->"Đang đua";case RESULT->"Kết quả";case WAITING->"Chờ vòng tiếp theo";};}
    boolean waiting(){return state==RaceState.WAITING;}String waitingMessage(){return Text.color("&eKeiba đang nghỉ. &fVòng #"+(raceId+1)+" mở sau &e"+secondsLeft()+" giây&f.");}
    RaceConditions conditions(){return conditions;}
    double stake(BetType type){return plugin.getConfig().getDouble("bet-types."+type.name()+".stake",plugin.getConfig().getDouble("economy.bet-unit",10000));}boolean enabled(BetType type){return plugin.getConfig().getBoolean("bet-types."+type.name()+".enabled",true);}
    double odds(BetType type,List<Integer> choices,boolean add){try{String key=type.key(choices);Map<String,Double> pools=repository.pools(raceId,type);double total=repository.totalPool(raceId,type)+houseSeed(type)+(add?stake(type):0),winning=pools.getOrDefault(key,0.0)+(add?stake(type):0);return adjustedOdds(type,total,winning);}catch(Exception e){return 0;}}
    String placeBet(Player player,BetType type,List<Integer> choices){if(state!=RaceState.BETTING_OPEN)return Text.color("&cCổng cược đã đóng.");if(!enabled(type))return Text.color("&cLoại cược này đang tắt.");if(choices.size()!=type.selections||new HashSet<>(choices).size()!=choices.size()||choices.stream().anyMatch(n->findHorse(n)==null))return Text.color("&cLựa chọn không hợp lệ.");try{int max=plugin.getConfig().getInt("economy.max-tickets-per-player",5);if(repository.ticketCount(raceId,player.getUniqueId())>=max)return Text.color("&cBạn đã đạt giới hạn "+max+" vé.");double amount=stake(type);if(!economy.has(player,amount))return Text.color("&cKhông đủ "+money(amount)+".");double projected=odds(type,choices,true);var tx=economy.withdrawPlayer(player,amount);if(!tx.transactionSuccess())return Text.color("&cTrừ tiền thất bại.");try{String key=type.key(choices);long id=repository.insertTicket(raceId,player.getUniqueId(),player.getName(),type,key,amount,projected);repository.audit(raceId,player.getName(),"BET",type+":"+key+":"+amount);return Text.color("&aĐã mua vé #"+id+" &e"+type.label+" &f"+selectionName(key)+" &7("+money(amount)+", odds tạm tính x"+fmt(projected)+")");}catch(Exception e){economy.depositPlayer(player,amount);throw e;}}catch(Exception e){plugin.getLogger().severe("Không thể đặt cược: "+e.getMessage());return Text.color("&cKhông thể ghi vé; tiền đã được hoàn nếu đã trừ.");}}
    List<BetTicket> playerTickets(UUID id){try{return repository.playerTickets(raceId,id);}catch(Exception e){return List.of();}}List<RaceRepository.RaceHistory> history(){try{return repository.history(plugin.getConfig().getInt("history.keep-last",30));}catch(Exception e){return List.of();}}RaceRepository.PlayerStats stats(UUID id){try{return repository.stats(id);}catch(Exception e){return new RaceRepository.PlayerStats(0,0,0,0);}}
    List<BetTicket> marketTickets(BetType type){try{return repository.tickets(raceId).stream().filter(ticket->ticket.type()==type).toList();}catch(Exception e){return List.of();}}double marketPlayerPool(BetType type){try{return repository.totalPool(raceId,type);}catch(Exception e){return 0;}}
    List<BetTicket> playerTicketsForRace(long race,UUID player){try{return repository.playerTickets(race,player);}catch(Exception e){return List.of();}}String horseDisplay(int number){HorseEntry horse=findHorse(number);return horse==null?"#"+number:"#"+number+" "+horse.name();}
    String adminReset(String scope,String actor){try{var backup=repository.backup(plugin.getDataFolder().toPath().resolve("backups"));switch(scope){case "current"->{cancelAndRefund(actor);return "Đã hoàn vé và tạo lại vòng hiện tại. Backup: "+backup.getFileName();}case "history"->repository.resetHistory();case "stats"->repository.resetStats();case "all"->{refund(raceId);repository.resetAll();openRace();}default->{return "Phạm vi reset không hợp lệ.";}}repository.audit(raceId,actor,"ADMIN_RESET",scope);return "Đã reset "+scope+". Backup: "+backup.getFileName();}catch(Exception e){plugin.getLogger().severe("Reset thất bại: "+e.getMessage());return "Reset thất bại: "+e.getMessage();}}
    void forceStart(){if(state==RaceState.BETTING_OPEN){deadline=0;tick();}}void cancelAndRefund(String actor){try{refund(raceId);repository.audit(raceId,actor,"ADMIN_CANCEL","Hoàn vé");openRace();}catch(Exception e){plugin.getLogger().severe(e.getMessage());}}
    private void tick(){if(System.currentTimeMillis()>=deadline)try{switch(state){case BETTING_OPEN->lock();case BETTING_LOCKED->run();case RUNNING->settle();case RESULT->{if(intervalMode())beginWaiting();else openRace();}case WAITING->openRace();}}catch(Exception e){plugin.getLogger().severe("Lỗi vòng #"+raceId+": "+e.getMessage());e.printStackTrace();}bossBar.update(this);}
    private void openRace()throws Exception{seed=random.nextLong();conditions=RaceConditions.select(plugin,seed);long duration=seconds("schedule.betting-seconds",180);deadline=System.currentTimeMillis()+duration*1000;raceId=repository.createRace(seed,hash(seed),deadline);state=RaceState.BETTING_OPEN;result=List.of();lastOdds=0;broadcast("&6[KIR Keiba] &aMở cược vòng #"+raceId+". &7"+conditions.distance().meters()+"m • "+conditions.surface().displayName()+" • "+conditions.track().displayName()+" • "+conditions.weather().displayName()+". &fDùng /keiba");sound("sounds.open","NONE");}
    private void beginWaiting(){state=RaceState.WAITING;deadline=System.currentTimeMillis()+seconds("schedule.interval-seconds",300)*1000;broadcast("&6[KIR Keiba] &7Vòng tiếp theo mở sau &e"+seconds("schedule.interval-seconds",300)+" giây&7.");}
    private boolean intervalMode(){return plugin.getConfig().getString("schedule.mode","CONTINUOUS").equalsIgnoreCase("INTERVAL");}
    private void lock()throws Exception{state=RaceState.BETTING_LOCKED;repository.updateState(raceId,state);deadline=System.currentTimeMillis()+seconds("schedule.locked-seconds",15)*1000;broadcast("&6[KIR Keiba] &eĐã khóa cược vòng #"+raceId+".");sound("sounds.lock","NONE");}
    private void run()throws Exception{state=RaceState.RUNNING;repository.updateState(raceId,state);List<Integer> order=new RaceSimulator().simulate(horses,seed,plugin.getConfig().getInt("race.simulation-steps",35),conditions).finishOrder();result=order.stream().map(this::findHorse).toList();deadline=System.currentTimeMillis()+seconds("schedule.running-seconds",35)*1000;sound("sounds.start","NONE");}
    private void settle()throws Exception{List<BetTicket> tickets=repository.tickets(raceId);Map<Long,Double> payouts=new HashMap<>(),odds=new HashMap<>();for(BetType type:BetType.values()){List<BetTicket> market=tickets.stream().filter(t->t.type()==type).toList();double total=market.stream().mapToDouble(BetTicket::stake).sum()+houseSeed(type);double winning=market.stream().filter(t->type.wins(t.selection(),result)).mapToDouble(BetTicket::stake).sum();double marketOdds=adjustedOdds(type,total,winning);for(BetTicket ticket:market){boolean win=type.wins(ticket.selection(),result);payouts.put(ticket.id(),win?ticket.stake()*marketOdds:0.0);odds.put(ticket.id(),win?marketOdds:0.0);}}repository.settle(raceId,result,payouts,odds);for(BetTicket ticket:tickets){double pay=payouts.getOrDefault(ticket.id(),0.0);if(pay>0)economy.depositPlayer(Bukkit.getOfflinePlayer(ticket.playerId()),pay);}state=RaceState.RESULT;deadline=System.currentTimeMillis()+seconds("schedule.result-seconds",30)*1000;lastOdds=0;broadcast("&6[KIR Keiba] &fKết quả: &e"+result.get(0).name()+" &7> &e"+result.get(1).name()+" &7> &e"+result.get(2).name());sound("sounds.result","UI_TOAST_CHALLENGE_COMPLETE");}
    private void recover()throws Exception{for(var r:repository.pendingRaces())refund(r.id());}private void refund(long id)throws Exception{for(BetTicket t:repository.tickets(id))if(!t.settled())economy.depositPlayer(Bukkit.getOfflinePlayer(t.playerId()),t.stake());repository.markRefunded(id);}
    private void loadHorses(){List<Map<?,?>> list=plugin.getConfig().getMapList("horses");if(list.size()<3)throw new IllegalStateException("Cần ít nhất 3 ngựa");int n=1;for(Map<?,?> v:list){horses.add(new HorseEntry(n,String.valueOf(value(v,"name","Ngựa "+n)),RunningStyle.valueOf(String.valueOf(value(v,"style","SENKO"))),number(v.get("power"),1),number(v.get("stamina"),1),number(v.get("finish"),1)));n++;}}
    HorseEntry findHorse(int n){return horses.stream().filter(h->h.number()==n).findFirst().orElse(null);}String selectionName(String key){return BetType.parse(key).stream().map(n->"#"+n+" "+findHorse(n).name()).reduce((a,b)->a+" → "+b).orElse(key);}double totalPool(){try{return repository.totalPool(raceId);}catch(Exception e){return 0;}}
    double houseSeed(BetType type){return Math.max(0,plugin.getConfig().getDouble("economy.house-seed-pool."+type.name(),0));}private double minimumOdds(BetType type){return Math.max(0,plugin.getConfig().getDouble("economy.minimum-odds."+type.name(),1));}private double maximumOdds(BetType type){return Math.max(minimumOdds(type),plugin.getConfig().getDouble("economy.maximum-odds."+type.name(),100));}private double adjustedOdds(BetType type,double total,double winning){return PoolMath.decimalOdds(total,winning,edge(),minimumOdds(type),maximumOdds(type));}
    private double edge(){return plugin.getConfig().getDouble("economy.house-edge",.15);}private long seconds(String p,long d){return plugin.getConfig().getLong(p,d);}private void broadcast(String s){Bukkit.broadcastMessage(Text.color(s));}private void sound(String path,String fallback){if(!plugin.getConfig().contains(path,true))return;String configured=plugin.getConfig().getString(path);if(configured==null||configured.isBlank()||configured.equalsIgnoreCase("NONE")||configured.equalsIgnoreCase("OFF"))return;try{Sound s=Sound.valueOf(configured.toUpperCase(Locale.ROOT));for(Player p:Bukkit.getOnlinePlayers())p.playSound(p.getLocation(),s,1,1);}catch(Exception ignored){}}private static Object value(Map<?,?>m,String k,Object d){return m.get(k)==null?d:m.get(k);}private static double number(Object v,double d){return v instanceof Number n?n.doubleValue():d;}static String money(double v){return String.format("%,.0f$",v);}static String fmt(double v){return String.format("%.2f",v);}private static String hash(long s)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(Long.toString(s).getBytes(StandardCharsets.UTF_8)));}
}
