package vn.kir.keiba;

import java.nio.file.*;import java.sql.*;import java.time.Instant;import java.util.*;

final class RaceRepository implements AutoCloseable {
    record PendingRace(long id,String state){}
    record RaceHistory(long id,int first,int second,int third,double pool,double paid,long settledAt){}
    record PlayerStats(long tickets,long wins,double staked,double paid){double profit(){return paid-staked;}}
    private final Connection connection;
    RaceRepository(Path folder)throws Exception{Files.createDirectories(folder);Class.forName("org.sqlite.JDBC");connection=DriverManager.getConnection("jdbc:sqlite:"+folder.resolve("keiba.db").toAbsolutePath());try(Statement s=connection.createStatement()){s.execute("PRAGMA journal_mode=WAL");s.execute("PRAGMA foreign_keys=ON");s.execute("PRAGMA busy_timeout=5000");s.executeUpdate("""
            CREATE TABLE IF NOT EXISTS races(id INTEGER PRIMARY KEY AUTOINCREMENT,state TEXT NOT NULL,seed INTEGER NOT NULL,seed_hash TEXT NOT NULL,opened_at INTEGER NOT NULL,close_at INTEGER NOT NULL,horse_first INTEGER,horse_second INTEGER,horse_third INTEGER,total_pool REAL NOT NULL DEFAULT 0,paid_pool REAL NOT NULL DEFAULT 0,settled_at INTEGER)
            """);s.executeUpdate("""
            CREATE TABLE IF NOT EXISTS tickets(id INTEGER PRIMARY KEY AUTOINCREMENT,race_id INTEGER NOT NULL REFERENCES races(id),player_uuid TEXT NOT NULL,player_name TEXT NOT NULL,horse_a INTEGER NOT NULL DEFAULT 0,horse_b INTEGER NOT NULL DEFAULT 0,bet_type TEXT NOT NULL DEFAULT 'UMAREN',selection_key TEXT,stake REAL NOT NULL,odds_at_bet REAL NOT NULL,odds_at_close REAL,payout REAL NOT NULL DEFAULT 0,settled INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL)
            """);s.executeUpdate("CREATE TABLE IF NOT EXISTS audit_log(id INTEGER PRIMARY KEY AUTOINCREMENT,created_at INTEGER NOT NULL,action TEXT NOT NULL,race_id INTEGER,actor TEXT NOT NULL,detail TEXT NOT NULL)");}
        addColumn("races","horse_third","INTEGER");addColumn("tickets","bet_type","TEXT NOT NULL DEFAULT 'UMAREN'");addColumn("tickets","selection_key","TEXT");try(Statement s=connection.createStatement()){s.executeUpdate("UPDATE tickets SET bet_type='UMAREN' WHERE bet_type IS NULL OR bet_type='' ");s.executeUpdate("UPDATE tickets SET selection_key=MIN(horse_a,horse_b)||'-'||MAX(horse_a,horse_b) WHERE selection_key IS NULL");s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_ticket_race_type ON tickets(race_id,bet_type)");s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_ticket_player ON tickets(player_uuid,race_id)");}}
    private void addColumn(String table,String column,String definition)throws SQLException{boolean found=false;try(Statement s=connection.createStatement();ResultSet rs=s.executeQuery("PRAGMA table_info("+table+")")){while(rs.next())if(rs.getString("name").equalsIgnoreCase(column))found=true;}if(!found)try(Statement s=connection.createStatement()){s.executeUpdate("ALTER TABLE "+table+" ADD COLUMN "+column+" "+definition);}}
    synchronized long createRace(long seed,String hash,long closeAt)throws SQLException{try(PreparedStatement p=connection.prepareStatement("INSERT INTO races(state,seed,seed_hash,opened_at,close_at) VALUES(?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){p.setString(1,RaceState.BETTING_OPEN.name());p.setLong(2,seed);p.setString(3,hash);p.setLong(4,Instant.now().toEpochMilli());p.setLong(5,closeAt);p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){if(!r.next())throw new SQLException("Không lấy được race ID");return r.getLong(1);}}}
    synchronized long insertTicket(long race,UUID uuid,String name,BetType type,String selection,double stake,double odds)throws SQLException{List<Integer> horses=BetType.parse(selection);int a=horses.get(0),b=horses.size()>1?horses.get(1):0;try(PreparedStatement p=connection.prepareStatement("INSERT INTO tickets(race_id,player_uuid,player_name,horse_a,horse_b,bet_type,selection_key,stake,odds_at_bet,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){p.setLong(1,race);p.setString(2,uuid.toString());p.setString(3,name);p.setInt(4,a);p.setInt(5,b);p.setString(6,type.name());p.setString(7,selection);p.setDouble(8,stake);p.setDouble(9,odds);p.setLong(10,Instant.now().toEpochMilli());p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){if(!r.next())throw new SQLException("Không lấy được ticket ID");return r.getLong(1);}}}
    synchronized int ticketCount(long race,UUID uuid)throws SQLException{return intQuery("SELECT COUNT(*) FROM tickets WHERE race_id=? AND player_uuid=?",race,uuid.toString());}
    synchronized List<BetTicket> tickets(long race)throws SQLException{return queryTickets("SELECT * FROM tickets WHERE race_id=? ORDER BY id",race,null);}
    synchronized List<BetTicket> playerTickets(long race,UUID uuid)throws SQLException{return queryTickets("SELECT * FROM tickets WHERE race_id=? AND player_uuid=? ORDER BY id",race,uuid.toString());}
    private List<BetTicket> queryTickets(String sql,long race,String uuid)throws SQLException{List<BetTicket> out=new ArrayList<>();try(PreparedStatement p=connection.prepareStatement(sql)){p.setLong(1,race);if(uuid!=null)p.setString(2,uuid);try(ResultSet r=p.executeQuery()){while(r.next())out.add(new BetTicket(r.getLong("id"),r.getLong("race_id"),UUID.fromString(r.getString("player_uuid")),r.getString("player_name"),BetType.valueOf(r.getString("bet_type")),r.getString("selection_key"),r.getDouble("stake"),r.getDouble("odds_at_bet"),r.getInt("settled")!=0,r.getDouble("payout")));}}return out;}
    synchronized Map<String,Double> pools(long race,BetType type)throws SQLException{Map<String,Double> out=new LinkedHashMap<>();try(PreparedStatement p=connection.prepareStatement("SELECT selection_key,SUM(stake) FROM tickets WHERE race_id=? AND bet_type=? GROUP BY selection_key")){p.setLong(1,race);p.setString(2,type.name());try(ResultSet r=p.executeQuery()){while(r.next())out.put(r.getString(1),r.getDouble(2));}}return out;}
    synchronized double totalPool(long race,BetType type)throws SQLException{return doubleQuery("SELECT COALESCE(SUM(stake),0) FROM tickets WHERE race_id=? AND bet_type=?",race,type.name());}
    synchronized double totalPool(long race)throws SQLException{return doubleQuery("SELECT COALESCE(SUM(stake),0) FROM tickets WHERE race_id=?",race,null);}
    synchronized void updateState(long race,RaceState state)throws SQLException{try(PreparedStatement p=connection.prepareStatement("UPDATE races SET state=? WHERE id=?")){p.setString(1,state.name());p.setLong(2,race);p.executeUpdate();}}
    synchronized void settle(long race,List<HorseEntry> order,Map<Long,Double> payouts,Map<Long,Double> odds)throws SQLException{connection.setAutoCommit(false);try{try(PreparedStatement p=connection.prepareStatement("UPDATE tickets SET odds_at_close=?,payout=?,settled=1 WHERE id=?")){for(long id:payouts.keySet()){p.setDouble(1,odds.getOrDefault(id,0.0));p.setDouble(2,payouts.get(id));p.setLong(3,id);p.addBatch();}p.executeBatch();}try(PreparedStatement p=connection.prepareStatement("UPDATE races SET state='RESULT',horse_first=?,horse_second=?,horse_third=?,total_pool=?,paid_pool=?,settled_at=? WHERE id=?")){p.setInt(1,order.get(0).number());p.setInt(2,order.get(1).number());p.setInt(3,order.get(2).number());p.setDouble(4,totalPool(race));p.setDouble(5,payouts.values().stream().mapToDouble(Double::doubleValue).sum());p.setLong(6,Instant.now().toEpochMilli());p.setLong(7,race);p.executeUpdate();}connection.commit();}catch(SQLException e){connection.rollback();throw e;}finally{connection.setAutoCommit(true);}}
    synchronized List<PendingRace> pendingRaces()throws SQLException{List<PendingRace> out=new ArrayList<>();try(Statement p=connection.createStatement();ResultSet r=p.executeQuery("SELECT id,state FROM races WHERE settled_at IS NULL")){while(r.next())out.add(new PendingRace(r.getLong(1),r.getString(2)));}return out;}
    synchronized void markRefunded(long race)throws SQLException{try(PreparedStatement p=connection.prepareStatement("UPDATE tickets SET settled=1,payout=stake,odds_at_close=1 WHERE race_id=?")){p.setLong(1,race);p.executeUpdate();}try(PreparedStatement p=connection.prepareStatement("UPDATE races SET state='RESULT',total_pool=(SELECT COALESCE(SUM(stake),0) FROM tickets WHERE race_id=?),paid_pool=(SELECT COALESCE(SUM(stake),0) FROM tickets WHERE race_id=?),settled_at=? WHERE id=?")){p.setLong(1,race);p.setLong(2,race);p.setLong(3,Instant.now().toEpochMilli());p.setLong(4,race);p.executeUpdate();}}
    synchronized List<RaceHistory> history(int limit)throws SQLException{List<RaceHistory> out=new ArrayList<>();try(PreparedStatement p=connection.prepareStatement("SELECT id,horse_first,horse_second,horse_third,total_pool,paid_pool,settled_at FROM races WHERE settled_at IS NOT NULL AND horse_first IS NOT NULL ORDER BY id DESC LIMIT ?")){p.setInt(1,limit);try(ResultSet r=p.executeQuery()){while(r.next())out.add(new RaceHistory(r.getLong(1),r.getInt(2),r.getInt(3),r.getInt(4),r.getDouble(5),r.getDouble(6),r.getLong(7)));}}return out;}
    synchronized PlayerStats stats(UUID uuid)throws SQLException{try(PreparedStatement p=connection.prepareStatement("SELECT COUNT(*),COALESCE(SUM(CASE WHEN payout>0 THEN 1 ELSE 0 END),0),COALESCE(SUM(stake),0),COALESCE(SUM(payout),0) FROM tickets WHERE player_uuid=? AND settled=1")){p.setString(1,uuid.toString());try(ResultSet r=p.executeQuery()){return r.next()?new PlayerStats(r.getLong(1),r.getLong(2),r.getDouble(3),r.getDouble(4)):new PlayerStats(0,0,0,0);}}}
    synchronized void audit(long race,String actor,String action,String detail)throws SQLException{try(PreparedStatement p=connection.prepareStatement("INSERT INTO audit_log(created_at,action,race_id,actor,detail) VALUES(?,?,?,?,?)")){p.setLong(1,Instant.now().toEpochMilli());p.setString(2,action);p.setLong(3,race);p.setString(4,actor);p.setString(5,detail);p.executeUpdate();}}
    synchronized Path backup(Path backupFolder)throws Exception{Files.createDirectories(backupFolder);Path target=backupFolder.resolve("keiba-"+Instant.now().toEpochMilli()+".db").toAbsolutePath();String escaped=target.toString().replace("'","''");try(Statement s=connection.createStatement()){s.execute("VACUUM INTO '"+escaped+"'");}return target;}
    synchronized void resetHistory()throws SQLException{try(Statement s=connection.createStatement()){s.executeUpdate("UPDATE races SET horse_first=NULL,horse_second=NULL,horse_third=NULL WHERE settled_at IS NOT NULL");}}
    synchronized void resetStats()throws SQLException{try(Statement s=connection.createStatement()){s.executeUpdate("DELETE FROM tickets WHERE settled=1");}}
    synchronized void resetAll()throws SQLException{connection.setAutoCommit(false);try(Statement s=connection.createStatement()){s.executeUpdate("DELETE FROM tickets");s.executeUpdate("DELETE FROM audit_log");s.executeUpdate("DELETE FROM races");s.executeUpdate("DELETE FROM sqlite_sequence WHERE name IN ('races','tickets','audit_log')");connection.commit();}catch(SQLException e){connection.rollback();throw e;}finally{connection.setAutoCommit(true);}}
    private int intQuery(String sql,Object a,Object b)throws SQLException{try(PreparedStatement p=connection.prepareStatement(sql)){p.setObject(1,a);p.setObject(2,b);try(ResultSet r=p.executeQuery()){return r.next()?r.getInt(1):0;}}}private double doubleQuery(String sql,Object a,Object b)throws SQLException{try(PreparedStatement p=connection.prepareStatement(sql)){p.setObject(1,a);if(b!=null)p.setObject(2,b);try(ResultSet r=p.executeQuery()){return r.next()?r.getDouble(1):0;}}}
    public synchronized void close()throws SQLException{connection.close();}
}
